### ISSUE TITLE
Miss compatibility with Beta 14

### ISSUE THREAD

**Issue by PeopleInside** [ReFlar/StopForumSpam#10]
Actually need to be compatible with Beta 14 https://discuss.flarum.org/d/25184-issues-on-upgrading/2
https://github.com/PeopleInside/Flarum_Beta14_Upgrade/issues/1

**Comment by luceos** [comment]
We are well aware that some extensions aren't up to date yet. Bumping them under our noses like this isn't really civil.

Please have patience for extensions to be slowly patched, provide funding so that we can dedicate paid hours to that through donating at https://opencollective.com/fof or provide a tested Pull Request for the upgrade of this extension.

Thank you for your understanding.

**Comment by PeopleInside** [comment]
Closing issue seems not nice to me @luceos I'm just trying to monitor, report and understand when will be able to update Flarum. Just this and if the extension is not compatible is an issue that I'm monitoring. Be unable to monitor an issue as is closed and not resolved is not nice but is my point of view.
